apiVersion: v1
kind: Service
metadata:
  name: info-app-service
  namespace: { { .Release.Namespace } }
spec:
  selector:
    app: info-app
  ports:
    - protocol: TCP
      port: { { .Values.service.port } }
      targetPort: 3000
  type: { { .Values.service.type } }
